version: '3.9'

networks:
  kafka-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          
services:
  
  kafka-1:
    
    networks:
      kafka-net:
        ipv4_address: ${KAFKA_HOST_1}
        
    image: ${KAFKA_IMAGE}
    ports:
      - "63796:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_HOST_1}:9093,1@${KAFKA_HOST_2}:9093,2@${KAFKA_HOST_3}:9093
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      # Listeners settings
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9095,CONTROLLER://:9093, EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://${KAFKA_HOST_1}:9092,CLIENT://:9095,EXTERNAL://${KAFKA_HOST_1}:63796
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,CLIENT:SASL_SSL,CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      # SASL settings
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CLIENT_LISTENER_NAME=CLIENT
      - KAFKA_CONTROLLER_USER=controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password
      - KAFKA_INTER_BROKER_USER=inter_broker_user
      - KAFKA_INTER_BROKER_PASSWORD=inter_broker_password
      # SSL settings
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=JKS
      # ACL
      - KAFKA_CFG_SUPER_USERS=User:user;User:controller_user;
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND="true"
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_EARLY_START_LISTENERS=CONTROLLER
    volumes:
      - "kafka_1_data:/bitnami/kafka"
      - "./scripts/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "./scripts/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
  
  kafka-2:
    
    networks:
      kafka-net:
        ipv4_address: ${KAFKA_HOST_2}
        
    image: ${KAFKA_IMAGE}
    ports:
      - "63797:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_HOST_1}:9093,1@${KAFKA_HOST_2}:9093,2@${KAFKA_HOST_3}:9093
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      # Listeners settings
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9095,CONTROLLER://:9093, EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://${KAFKA_HOST_1}:9092,CLIENT://:9095,EXTERNAL://${KAFKA_HOST_1}:63796
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,CLIENT:SASL_SSL,CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      # SASL settings
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CLIENT_LISTENER_NAME=CLIENT
      - KAFKA_CONTROLLER_USER=controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password
      - KAFKA_INTER_BROKER_USER=inter_broker_user
      - KAFKA_INTER_BROKER_PASSWORD=inter_broker_password
      # SSL settings
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=JKS
      # ACL
      - KAFKA_CFG_SUPER_USERS=User:user;User:controller_user;
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND="true"
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_EARLY_START_LISTENERS=CONTROLLER
    volumes:
      - "kafka_2_data:/bitnami/kafka"
      - "./scripts/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "./scripts/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"

  kafka-3:
    
    networks:
      kafka-net:
        ipv4_address: ${KAFKA_HOST_3}
        
    image: ${KAFKA_IMAGE}
    ports:
      - "63798:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_HOST_1}:9093,1@${KAFKA_HOST_2}:9093,2@${KAFKA_HOST_3}:9093
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      # Listeners settings
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:9095,CONTROLLER://:9093, EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://${KAFKA_HOST_1}:9092,CLIENT://:9095,EXTERNAL://${KAFKA_HOST_1}:63796
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_SSL,CLIENT:SASL_SSL,CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      # SASL settings
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CLIENT_LISTENER_NAME=CLIENT
      - KAFKA_CONTROLLER_USER=controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password
      - KAFKA_INTER_BROKER_USER=inter_broker_user
      - KAFKA_INTER_BROKER_PASSWORD=inter_broker_password
      # SSL settings
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=JKS
      # ACL
      - KAFKA_CFG_SUPER_USERS=User:user;User:controller_user;
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND="true"
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - KAFKA_CFG_EARLY_START_LISTENERS=CONTROLLER
    volumes:
      - "kafka_3_data:/bitnami/kafka"
      - "./scripts/keystore/kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "./scripts/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"

volumes:
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local
  kafka_3_data:
    driver: local