# set -x

export DEFAULT_MINIKUBE_PROFILE=dapr
export DEFAULT_MINIKUBE_NODES=1
export DEFAULT_MINIKUBE_RAM=32000mb
export DEFAULT_MINIKUBE_CPU=6
export DEFAULT_MINIKUBE_DISK=40g
export DEFAULT_MINIKUBE_VM_DRIVER=docker
export DEFAULT_MINIKUBE_STATIC_IP=192.168.200.200

export DEFAULT_TIMEOUT=180s